name: Build and Deploy
on:
  push:
    branches:
      - gh-page
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Ruby 2.7.8 ğŸ’
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8

      - name: Install and Build ğŸ”§
        run: |
          make install-deb
          make build
          
      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: master  # deploying branch
